---
- name: Main Playbook
  hosts: all
  become: true

  roles:
    - role: packages
      name: Most used packages
      tags:
        - packages
    
    - role: kitty
      name: Kitty terminal configuration
      tags:
        - kitty 

    - role: fastfetch
      name: Fastfetch configuration
      tags:
        - fastfetch
...