---
- name: Main Playbook
  hosts: all
  become: true

  roles:
    - role: packages
      name: Most used packages
      tags:
        - packages
    
    - role: kitty
      name: Kitty terminal configuration
      tags:
        - kitty 

    - role: fastfetch
      name: Fastfetch configuration
      tags:
        - fastfetch

    - role: niri
      name: Niri configuration
      tags:
        - niri
    
    - role: noctalia
      name: Nocatlia configuration
      tags:
        - noctalia
    
    - role: obsidian
      name: Obsidian configuration
      tags:
        - obsidian
    
    - role: vscode
      name: Visual Studio Code configuration
      tags:
        - vscode
    
    - role: zsh
      name: Zsh configuration
      tags:
        - zsh
...