- name: Load OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Include package manager specific tasks
  ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yml"

- name: Install Opencode
  ansible.builtin.npm:
    name: opencode-ai
    global: true
  become: true