#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/packages
packages_list:
  - kitty
  - neovim
  - niri
  - terraform
  - ansible
  - nvm
  - pip
  # - cmatrix
  - fastfetch

delete_packages_list:
  - cmatrix