# Font Configuration
font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0

background_opacity 0.75
dynamic_background_opacity yes

# Enable Font Ligatures
disable_ligatures never

# Window Layout & Aesthetics
hide_window_decorations yes
window_padding_width    0
window_margin_width     0
single_window_padding_width 0


