#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/fastfetch
- name: Set path variables
  ansible.builtin.set_fact:
    fastfetch_role_files: "{{ role_path }}/files"
    fastfetch_user_config: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/fastfetch"

- name: Ensure FastFetch directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ fastfetch_role_files }}"
    - "{{ fastfetch_user_config }}"

- name: Find all existing config files
  ansible.builtin.find:
    paths: "{{ fastfetch_user_config }}"
    hidden: yes
    recurse: yes
  register: local_fastfetch_files

- name: Show existing dotfiles
  ansible.builtin.debug:
    msg: "{{ item.path }}"
  loop: "{{ local_fastfetch_files.files }}"
  loop_control:
    label: "{{ item.path | relpath(fastfetch_user_config) }}"

- name: Import unmanaged ~/.config/fastfetch files into roles/fastfetch/files
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ fastfetch_role_files }}/{{ item.path | relpath(fastfetch_user_config) }}"
    remote_src: yes
    force: no
    mode: '0644'
  loop: "{{ local_fastfetch_files.files }}"
  loop_control:
    label: "{{ item.path | relpath(fastfetch_user_config) }}"

- name: Find all tracked files in roles/fastfetch/files
  ansible.builtin.find:
    paths: "{{ fastfetch_role_files }}"
    hidden: yes
    recurse: yes
    file_type: file
  register: role_fastfetch_files

- name: Ensure subdirectories exist in ~/.config/fastfetch
  ansible.builtin.file:
    src: "{{ fastfetch_user_config }}/{{ item.path | relpath(fastfetch_role_files) | dirname }}"
    state: directory
    mode: '0755'
  loop: "{{ role_fastfetch_files.files }}"
  when:
    - "(item.path | relpath(fastfetch_role_files) | dirname) != '.' "
    - "(item.path | relpath(fastfetch_role_files) | dirname) != '' "
  loop_control:
    label: "{{ item.path | relpath(fastfetch_role_files) | dirname }}"

- name: Create symlink from ~/.config/fastfetch to role files
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "{{ fastfetch_user_config }}/{{item.path | relpath(fastfetch_role_files) }}"
    state: link
    force: yes
  loop: "{{ role_fastfetch_files.files }}"
  loop_control:
    label: "{{ item.path | relpath(fastfetch_role_files) }}"
